services:
    fos_message.provider.default:
        class: Awaresoft\MessageBundle\Provider\Provider
        public: false
        arguments:
            - "@fos_message.thread_manager"
            - "@fos_message.message_manager"
            - "@fos_message.thread_reader"
            - "@fos_message.authorizer"
            - "@fos_message.participant_provider"

    fos_message.message_manager.default:
        class: Awaresoft\MessageBundle\EntityManager\MessageManager
        public: false
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%fos_message.message_class%"
            - "%fos_message.message_meta_class%"

    fos_message.thread_manager.default:
        class: Awaresoft\MessageBundle\EntityManager\ThreadManager
        public: false
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%fos_message.thread_class%"
            - "%fos_message.thread_meta_class%"
            - "@fos_message.message_manager"

    fos_message.new_thread_form.type.default:
        class: Awaresoft\MessageBundle\FormType\NewThreadMessageFormType
        public: false
        calls:
            - [setContainer, ["@service_container"]]

    fos_message.reply_form.type.default:
        class: Awaresoft\MessageBundle\FormType\ReplyMessageFormType
        public: false
        calls:
            - [setContainer, ["@service_container"]]

    fos_message.new_thread_form.handler.default:
        class: Awaresoft\MessageBundle\FormHandler\NewThreadMessageFormHandler
        scope: request
        public: false
        arguments:
            - "@request"
            - "@fos_message.composer"
            - "@fos_message.sender"
            - "@fos_message.participant_provider"
            - "@service_container"

    fos_message.reply_form.handler.default:
        class: Awaresoft\MessageBundle\FormHandler\ReplyMessageFormHandler
        scope: request
        public: false
        arguments:
            - "@request"
            - "@fos_message.composer"
            - "@fos_message.sender"
            - "@fos_message.participant_provider"
            - "@service_container"


    fos_message.new_thread_form.factory.default:
        class: Awaresoft\MessageBundle\FormFactory\NewThreadMessageFormFactory
        public: false
        arguments:
            - "@form.factory"
            - "@fos_message.new_thread_form.type"
            - "%fos_message.new_thread_form.name%"
            - "%fos_message.new_thread_form.model%"

    fos_message.reply_form.factory.default:
        class: Awaresoft\MessageBundle\FormFactory\NewThreadMessageFormFactory
        public: false
        arguments:
            - "@form.factory"
            - "@fos_message.reply_form.type"
            - "%fos_message.reply_form.name%"
            - "%fos_message.reply_form.model%"